spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/OperaSalesDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.yaml
    enabled: true