version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "OperaSalesDB"
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge